### ISSUE TITLE
关于大约0.938的准确率？

### ISSUE THREAD

**Issue by chenynCV** [chenyuntc/scene-baseline#1]
你好，想请教一下，0.938这个准确率具体是什么过程得到的呢？有没有在imagenet或者place365上pretrain过？我用tensorflow版的resnet18，不用任何其它数据集做预训练，只用官方提供的训练集训练，官方提供的验证集测试，在训练集上准确率接近1.0，在验证集上top1大概只有0.6左右，top3大概只有0.8。。。。

**Comment by chenynCV** [comment]
0.6是top1，top3大概0.8

**Comment by chenyuntc** [comment]
使用imagenet的预训练模型，模型是resnet34。直接运行程序未手动调整。
你的准确率接近1可能数据增强没做好，导致过拟合

**Comment by chenynCV** [comment]
恩，谢谢回复了
